### ISSUE TITLE
How to Configure it for Internet 

### ISSUE THREAD

**Issue by John-Constantine** [werkamsus/Lilith#2]
Hi there, 

i am interested to test it on a network other than loop back (127.0.0.1) , is there a way to configure, any wiki or guideline are appreciated 

thanks

**Comment by werkamsus** [comment]
Yes, there is. You Need to edit the Settings.cpp file. Just skip through
the Video that is linked, i think around the 10 min Mark i go over the
Settings.

**Comment by John-Constantine** [comment]
thanks for you reply , i configured my ddns ip but its not working , any suggestion  ?

**Comment by werkamsus** [comment]
First of all: are you testing it in your own network with ddns? That for
example doesn't work for me, and if I recall correctly you can't establish
a connection from your network to your network via your external ip (the
one the internet sees).
Either test it on a local one (example: 192.0.0.1, 10.0.0.1) or place the
client on another network. An easy way to do that is to create a hotspot
with your mobile phone and connect to it via a laptop, then client and
server are on different networks and can 'see' each other through their
external ips.
And don't worry, in a real world non-testing environment, you probably
won't run into this issue, since your client will most likely be on another
network.

If that doesn't work:

Did you forward the port in your router? Is your ddns synced to your ip?
Is it working if you enter your ip directly?
I'll look into it today, but it should work just fine with a ddns.

Hope I could answer your question :)

**Comment by John-Constantine** [comment]
is MSVC.dll a dependency ?

i tried to install the released Lilith.exe on a machine but , i get this error 
**"This Program can't start becasue MSVCP140D.dll is missing from your computer. try reinstall the program to fix this problem"**

i google a for a while on the issue and this [Link](https://stackoverflow.com/questions/4668566/application-has-failed-to-start-because-msvcp100d-dll-was-not-found-reinstallin) gives some info that i figured out is better to ask you

thanks

**Comment by werkamsus** [comment]
You need to build it as non-debug. Even though you configure it for
release, Visual Studio still doesn't include some mandatory windows dll's.
To fix this go to:
Configuration Properties -> C/C++ -> Code Generation -> Runtime Library
And select Multi-Threaded (/MT) instead of Multi-Threaded-Debug (/MTd).

**Comment by John-Constantine** [comment]
Thank you so much for instant help,

now its not giving any error , when run on another machine , but i think something is still there to fix as its not listed in server console

**Comment by werkamsus** [comment]
Be reminded that you need to be on another network, not just on another
machine. Try to `ping` the server from the client in cmd.exe.
If you don't get a response / no bytes are returned, then the link itself
is faulty.

**Comment by John-Constantine** [comment]
i am using two different networks, 
client PC is using Broadband Leased Line
server PC is using different WiFi , 
i have forwarded port on router ,
i have configured my ddns ip in the code

but no luck so  far

can you suggest something

**Comment by werkamsus** [comment]
Which 'client' are you executing? I think that might have something to do with your other issue.
You need to execute Server.exe on the server pc and forward the port in the firewall of that network.
Then you need to execute the client (might be called winlive.exe or Lilith.exe) on a different network.
I think you might have forwarded the port on the wrong end or executed a different file on the client end.

**Comment by John-Constantine** [comment]
well dear **Werkamsus** , i have been working on such kind of projects from sometime, so i have idea about what end should be server operated, port forwarded from, anyway thanks for pointing this stuff out it might be useful for someone in future. 

**Is Lilith  with ddns working for you ?** 

thanks

**Comment by werkamsus** [comment]
I wasn't questioning your ability, but merely trying to the error. Setting it up with ddns doesn't change anything. What a ddns does is it simply creates a fixed address that then translates to your ip. So in the end, the client still connects to x.x.x.x, whether it's via the address sample.ddns.net or directly.

**Comment by John-Constantine** [comment]
i tried everything, still i am not able to get it working using ddns, can you suggest something , thanks
